[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./" }, { access = "read", path = "/root/.nodes" }]
solc = "0.8.27"
via-ir = true
optimizer = true
optimizer_runs = 1000000
 # Higher number optimizes for frequent contract calls, lower number optimizes for deployment cost


remappings = [
    "@eigenlayer/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/src/",
    "@eigenlayer-scripts/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/script/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/",
    "@openzeppelin/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/",
    "@openzeppelin-upgrades/=lib/eigenlayer-middleware/lib/eigenlayer-contracts/lib/openzeppelin-contracts-upgradeable-v4.9.0/",
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
multiline_func_header = "params_first"
number_underscore = "thousands"
